/*
    Author: Jessmer John Palanca
    Section: CSC337 Web Programming SPRING2019, Homework 3
    Filename: guessingGame.js
    Description: The javascript file for the guessingGame.html
*/

'use strict';

(function() {
    // initializing the random number, globally
    let randNum = 0;

    // when the page is loaded, do this function
    window.onload = function() {
        let startButton = document.getElementById("start");
        startButton.onclick = randomNumber;
    };

    /**
      * When the start button is pressed, this function takes the minimum and Maximum
      * value inputs and generates a random number. The random number will then be
      * stored the global variable called "randNum". After generating the number, the
      * user will now be able to guess the random number.
    */
    function randomNumber() {

        /* if the "start" button is pressed, the previous guess history will all be
           removed and then generates a new randon number */
        let reset = document.getElementById("history");
        reset.innerHTML = "";

        let min = parseInt(document.getElementById('min').value);
        let max = parseInt(document.getElementById('max').value) + 1;
        randNum = parseInt(Math.floor(Math.random() * (max - min)) + min);

        let guessButton = document.getElementById("guess");
        guessButton.onclick = userGuess;
    }

    /**
      * This function process the user's guess number. When the "guess" button is
      * pressed, the function takes the guess value and compare it to the random number
      * generated by the computer. After comparing both values, the computer will then
      * generate a hint messages. If the user guessed the number correctly, it will
      * generate a message saying "you got it right!". These messages will be displayed
      * on "Your previous guesses" section of the page. The new messages will be
      * displayed on the top of the message section.
    */
    function userGuess(){
        let guessNum = parseInt(document.getElementById('guessNumber').value);
        // creating a new item on the list
        let newItem = document.createElement("LI");

        // conditional statements
        if (guessNum === randNum){
            let text = document.createTextNode('you got it right!');
            // add the string into the list
            newItem.appendChild(text);
        }
        else if(guessNum < randNum){
            let text = document.createTextNode('more than ' + guessNum);
            newItem.appendChild(text);
        }
        else if (guessNum > randNum) {
            let text = document.createTextNode('less than ' + guessNum);
            newItem.appendChild(text);
        }

        // adding the new item on top of the list
        let list = document.getElementById('history');
        list.insertBefore(newItem, list.childNodes[0]);
    }
})();
